name: Deploy to Salesforce Org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Check If CLI Installed
        run: sf version
      
      - name: Check if Secret exists
        run: echo "Checking if SF_CONSUMER_KEY secret exists..." && \
              if [ -z "${{ secrets.SF_CONSUMER_KEY }}" ]; then \
                echo "Error: SF_CONSUMER_KEY secret is not set." && exit 1; \
              else \
                echo "SF_CONSUMER_KEY secret is set."; \
              fi 